# Generated by Django 3.0.5 on 2020-04-28 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 28, 19, 1, 12, 744726, tzinfo=utc))),
                ('makes', models.PositiveIntegerField()),
            ],
        ),
    ]
