# Generated by Django 3.0.5 on 2020-04-29 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0002_auto_20200429_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 29)),
        ),
    ]
