# Generated by Django 3.0.5 on 2020-04-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0003_auto_20200429_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='makes',
        ),
    ]
