# Generated by Django 3.0.5 on 2020-04-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0004_remove_practice_makes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='attempts_made',
            new_name='attempts',
        ),
    ]
