# Generated by Django 3.0.5 on 2020-04-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0005_auto_20200429_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shots', models.PositiveIntegerField()),
                ('total_made', models.PositiveIntegerField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoops.Practice')),
            ],
        ),
    ]
