# Generated by Django 3.0.6 on 2020-05-07 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0006_basicstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('conditions', models.CharField(max_length=127)),
                ('humidity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 7)),
        ),
    ]
