# Generated by Django 3.0.6 on 2020-05-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0007_auto_20200507_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherconditions',
            name='practice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hoops.Practice'),
        ),
    ]
