# Generated by Django 3.0.6 on 2020-05-08 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoops', '0008_weatherconditions_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 8)),
        ),
    ]
