# Generated by Django 3.0.6 on 2020-05-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0011_auto_20200509_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(),
        ),
    ]
